name: gaussian-brush-2d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=12.1
  - torchvision
  - numpy=1.24
  - scipy
  - pillow
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - websockets==12.0
    - python-multipart==0.0.6
    - opencv-python==4.8.1.78
    - plyfile==1.0.3
